### PR TITLE
update rather than replace passwd file

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/s2i-python/issues/98

### CODE REVIEW

**Comment by bparees** [comment]
@GrahamDumpleton @mfojtik ptal.

@GrahamDumpleton this pretty much uses the code you provided in the issue (thanks!)

**Comment by bparees** [comment]
(will do follow on pulls to other repos once this merges)

**Comment by mfojtik** [comment]
LGTM.

**Comment by mfojtik** [comment]
will wait for @GrahamDumpleton :-)

**Comment by GrahamDumpleton** [comment]
What are you waiting for from me on this one?

**Comment by mfojtik** [comment]
@GrahamDumpleton does it look good to you?

**Comment by GrahamDumpleton** [comment]
Of what I remember of this, yes, looks okay.

**Pull request merged**
